# Generated by Django 6.0.2 on 2026-02-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blog_is_active_blog_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
