# Generated by Django 6.0.2 on 2026-02-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_blogimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogimage",
            options={},
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
        migrations.RemoveField(
            model_name="blogimage",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="featured/"),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="api.blog",
            ),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
    ]
