# Generated by Django 6.0.2 on 2026-02-17 00:00

from django.db import migrations, models
from django.utils.text import slugify


def _generate_unique_slug(model, name, instance_id):
    base_slug = slugify(name) or "item"
    slug = base_slug
    counter = 1
    queryset = model.objects.all().exclude(pk=instance_id)
    while queryset.filter(slug=slug).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    return slug


def populate_slugs(apps, schema_editor):
    BlogCategory = apps.get_model("api", "BlogCategory")
    BlogTag = apps.get_model("api", "BlogTag")

    for category in BlogCategory.objects.all():
        if not category.slug:
            category.slug = _generate_unique_slug(BlogCategory, category.name, category.pk)
            category.save(update_fields=["slug"])

    for tag in BlogTag.objects.all():
        if not tag.slug:
            tag.slug = _generate_unique_slug(BlogTag, tag.name, tag.pk)
            tag.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_blogimage_blog_blog_gallery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blogtag",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
