# Generated by Django 6.0.2 on 2026-02-17 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_slug_to_category_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="featured/"
            ),
            preserve_default=False,
        ),
    ]
