# Generated by Django 6.0.2 on 2026-02-12 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_blogimage_options_remove_blog_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogimage",
            name="blog",
        ),
        migrations.AddField(
            model_name="blog",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="api.blogimage"
            ),
        ),
        migrations.AddField(
            model_name="blogimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
