# Generated by Django 6.0.2 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_blog_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogtag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
