# Generated by Django 6.0.2 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_update_updated_at_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
