# Generated by Django 6.0.2 on 2026-03-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_blog_author_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billingType",
                    models.CharField(
                        choices=[("1-15", "1-15"), ("16-30", "16-30")],
                        default="1-15",
                        max_length=15,
                    ),
                ),
                ("userSetting", models.TextField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "whichUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAdvertisementTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loginTime", models.DateTimeField(blank=True, null=True)),
                ("logoutTime", models.DateTimeField(blank=True, null=True)),
                ("lastSyncTime", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("redisDuration", models.IntegerField(default=0)),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "linkUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adTransactionLinkUser",
                        to="api.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licenseKey", models.CharField(max_length=20, unique=True)),
                (
                    "deviceSerialNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("licenseUseTime", models.DateTimeField(blank=True, null=True)),
                ("licenseGenerateTime", models.DateTimeField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("isSuspended", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "generatedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linkUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userinfo",
                    ),
                ),
            ],
        ),
    ]
